// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Item: typeof import('./src/components/ToDoList/item.vue')['default']
    ToDoInput: typeof import('./src/components/ToDoInput/index.vue')['default']
    ToDoList: typeof import('./src/components/ToDoList/index.vue')['default']
  }
}
